version: '3'

services:
  database:
    image: "postgres:11.1-alpine"
    ports:
        - 5445:5432
    # env_file:
    #     - .env
    container_name: "test_postgraphile"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
